// Code generated by mockery v2.53.3. DO NOT EDIT.

package controller

import (
	context "context"

	v1 "github.com/cloudogu/k8s-auth-registration-lib/api/v1"
	domain "github.com/cloudogu/k8s-auth-registration-operator/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockSecretReconciler is an autogenerated mock type for the secretReconciler type
type mockSecretReconciler struct {
	mock.Mock
}

type mockSecretReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSecretReconciler) EXPECT() *mockSecretReconciler_Expecter {
	return &mockSecretReconciler_Expecter{mock: &_m.Mock}
}

// Reconcile provides a mock function with given fields: ctx, regResult, authRegistration, secretName, controllerManagedSecret
func (_m *mockSecretReconciler) Reconcile(ctx context.Context, regResult domain.RegistrationResult, authRegistration *v1.AuthRegistration, secretName string, controllerManagedSecret bool) error {
	ret := _m.Called(ctx, regResult, authRegistration, secretName, controllerManagedSecret)

	if len(ret) == 0 {
		panic("no return value specified for Reconcile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RegistrationResult, *v1.AuthRegistration, string, bool) error); ok {
		r0 = rf(ctx, regResult, authRegistration, secretName, controllerManagedSecret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockSecretReconciler_Reconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconcile'
type mockSecretReconciler_Reconcile_Call struct {
	*mock.Call
}

// Reconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - regResult domain.RegistrationResult
//   - authRegistration *v1.AuthRegistration
//   - secretName string
//   - controllerManagedSecret bool
func (_e *mockSecretReconciler_Expecter) Reconcile(ctx interface{}, regResult interface{}, authRegistration interface{}, secretName interface{}, controllerManagedSecret interface{}) *mockSecretReconciler_Reconcile_Call {
	return &mockSecretReconciler_Reconcile_Call{Call: _e.mock.On("Reconcile", ctx, regResult, authRegistration, secretName, controllerManagedSecret)}
}

func (_c *mockSecretReconciler_Reconcile_Call) Run(run func(ctx context.Context, regResult domain.RegistrationResult, authRegistration *v1.AuthRegistration, secretName string, controllerManagedSecret bool)) *mockSecretReconciler_Reconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.RegistrationResult), args[2].(*v1.AuthRegistration), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *mockSecretReconciler_Reconcile_Call) Return(_a0 error) *mockSecretReconciler_Reconcile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockSecretReconciler_Reconcile_Call) RunAndReturn(run func(context.Context, domain.RegistrationResult, *v1.AuthRegistration, string, bool) error) *mockSecretReconciler_Reconcile_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSecretReconciler creates a new instance of mockSecretReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSecretReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSecretReconciler {
	mock := &mockSecretReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
