// Code generated by mockery v2.53.3. DO NOT EDIT.

package controller

import (
	context "context"

	domain "github.com/cloudogu/k8s-auth-registration-operator/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockServiceRegistrationBackend is an autogenerated mock type for the serviceRegistrationBackend type
type mockServiceRegistrationBackend struct {
	mock.Mock
}

type mockServiceRegistrationBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *mockServiceRegistrationBackend) EXPECT() *mockServiceRegistrationBackend_Expecter {
	return &mockServiceRegistrationBackend_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, registration
func (_m *mockServiceRegistrationBackend) Delete(ctx context.Context, registration domain.Registration) error {
	ret := _m.Called(ctx, registration)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Registration) error); ok {
		r0 = rf(ctx, registration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockServiceRegistrationBackend_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockServiceRegistrationBackend_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - registration domain.Registration
func (_e *mockServiceRegistrationBackend_Expecter) Delete(ctx interface{}, registration interface{}) *mockServiceRegistrationBackend_Delete_Call {
	return &mockServiceRegistrationBackend_Delete_Call{Call: _e.mock.On("Delete", ctx, registration)}
}

func (_c *mockServiceRegistrationBackend_Delete_Call) Run(run func(ctx context.Context, registration domain.Registration)) *mockServiceRegistrationBackend_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Registration))
	})
	return _c
}

func (_c *mockServiceRegistrationBackend_Delete_Call) Return(_a0 error) *mockServiceRegistrationBackend_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockServiceRegistrationBackend_Delete_Call) RunAndReturn(run func(context.Context, domain.Registration) error) *mockServiceRegistrationBackend_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, registration
func (_m *mockServiceRegistrationBackend) Upsert(ctx context.Context, registration domain.Registration) (domain.RegistrationResult, error) {
	ret := _m.Called(ctx, registration)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 domain.RegistrationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Registration) (domain.RegistrationResult, error)); ok {
		return rf(ctx, registration)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Registration) domain.RegistrationResult); ok {
		r0 = rf(ctx, registration)
	} else {
		r0 = ret.Get(0).(domain.RegistrationResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Registration) error); ok {
		r1 = rf(ctx, registration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockServiceRegistrationBackend_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type mockServiceRegistrationBackend_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - registration domain.Registration
func (_e *mockServiceRegistrationBackend_Expecter) Upsert(ctx interface{}, registration interface{}) *mockServiceRegistrationBackend_Upsert_Call {
	return &mockServiceRegistrationBackend_Upsert_Call{Call: _e.mock.On("Upsert", ctx, registration)}
}

func (_c *mockServiceRegistrationBackend_Upsert_Call) Run(run func(ctx context.Context, registration domain.Registration)) *mockServiceRegistrationBackend_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Registration))
	})
	return _c
}

func (_c *mockServiceRegistrationBackend_Upsert_Call) Return(_a0 domain.RegistrationResult, _a1 error) *mockServiceRegistrationBackend_Upsert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockServiceRegistrationBackend_Upsert_Call) RunAndReturn(run func(context.Context, domain.Registration) (domain.RegistrationResult, error)) *mockServiceRegistrationBackend_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// newMockServiceRegistrationBackend creates a new instance of mockServiceRegistrationBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockServiceRegistrationBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockServiceRegistrationBackend {
	mock := &mockServiceRegistrationBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
