// Code generated by mockery v2.53.3. DO NOT EDIT.

package controller

import (
	context "context"

	v1 "github.com/cloudogu/k8s-auth-registration-lib/api/v1"
	logr "github.com/go-logr/logr"
	mock "github.com/stretchr/testify/mock"
	reconcile "sigs.k8s.io/controller-runtime/pkg/reconcile"
)

// mockAuthRegistrationReconciler is an autogenerated mock type for the authRegistrationReconciler type
type mockAuthRegistrationReconciler struct {
	mock.Mock
}

type mockAuthRegistrationReconciler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAuthRegistrationReconciler) EXPECT() *mockAuthRegistrationReconciler_Expecter {
	return &mockAuthRegistrationReconciler_Expecter{mock: &_m.Mock}
}

// handleDeletion provides a mock function with given fields: ctx, authRegistration, logger
func (_m *mockAuthRegistrationReconciler) handleDeletion(ctx context.Context, authRegistration *v1.AuthRegistration, logger logr.Logger) (reconcile.Result, error) {
	ret := _m.Called(ctx, authRegistration, logger)

	if len(ret) == 0 {
		panic("no return value specified for handleDeletion")
	}

	var r0 reconcile.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.AuthRegistration, logr.Logger) (reconcile.Result, error)); ok {
		return rf(ctx, authRegistration, logger)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.AuthRegistration, logr.Logger) reconcile.Result); ok {
		r0 = rf(ctx, authRegistration, logger)
	} else {
		r0 = ret.Get(0).(reconcile.Result)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.AuthRegistration, logr.Logger) error); ok {
		r1 = rf(ctx, authRegistration, logger)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockAuthRegistrationReconciler_handleDeletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'handleDeletion'
type mockAuthRegistrationReconciler_handleDeletion_Call struct {
	*mock.Call
}

// handleDeletion is a helper method to define mock.On call
//   - ctx context.Context
//   - authRegistration *v1.AuthRegistration
//   - logger logr.Logger
func (_e *mockAuthRegistrationReconciler_Expecter) handleDeletion(ctx interface{}, authRegistration interface{}, logger interface{}) *mockAuthRegistrationReconciler_handleDeletion_Call {
	return &mockAuthRegistrationReconciler_handleDeletion_Call{Call: _e.mock.On("handleDeletion", ctx, authRegistration, logger)}
}

func (_c *mockAuthRegistrationReconciler_handleDeletion_Call) Run(run func(ctx context.Context, authRegistration *v1.AuthRegistration, logger logr.Logger)) *mockAuthRegistrationReconciler_handleDeletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.AuthRegistration), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockAuthRegistrationReconciler_handleDeletion_Call) Return(_a0 reconcile.Result, _a1 error) *mockAuthRegistrationReconciler_handleDeletion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockAuthRegistrationReconciler_handleDeletion_Call) RunAndReturn(run func(context.Context, *v1.AuthRegistration, logr.Logger) (reconcile.Result, error)) *mockAuthRegistrationReconciler_handleDeletion_Call {
	_c.Call.Return(run)
	return _c
}

// handleReconcile provides a mock function with given fields: ctx, authRegistration, logger
func (_m *mockAuthRegistrationReconciler) handleReconcile(ctx context.Context, authRegistration *v1.AuthRegistration, logger logr.Logger) error {
	ret := _m.Called(ctx, authRegistration, logger)

	if len(ret) == 0 {
		panic("no return value specified for handleReconcile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.AuthRegistration, logr.Logger) error); ok {
		r0 = rf(ctx, authRegistration, logger)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockAuthRegistrationReconciler_handleReconcile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'handleReconcile'
type mockAuthRegistrationReconciler_handleReconcile_Call struct {
	*mock.Call
}

// handleReconcile is a helper method to define mock.On call
//   - ctx context.Context
//   - authRegistration *v1.AuthRegistration
//   - logger logr.Logger
func (_e *mockAuthRegistrationReconciler_Expecter) handleReconcile(ctx interface{}, authRegistration interface{}, logger interface{}) *mockAuthRegistrationReconciler_handleReconcile_Call {
	return &mockAuthRegistrationReconciler_handleReconcile_Call{Call: _e.mock.On("handleReconcile", ctx, authRegistration, logger)}
}

func (_c *mockAuthRegistrationReconciler_handleReconcile_Call) Run(run func(ctx context.Context, authRegistration *v1.AuthRegistration, logger logr.Logger)) *mockAuthRegistrationReconciler_handleReconcile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.AuthRegistration), args[2].(logr.Logger))
	})
	return _c
}

func (_c *mockAuthRegistrationReconciler_handleReconcile_Call) Return(_a0 error) *mockAuthRegistrationReconciler_handleReconcile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockAuthRegistrationReconciler_handleReconcile_Call) RunAndReturn(run func(context.Context, *v1.AuthRegistration, logr.Logger) error) *mockAuthRegistrationReconciler_handleReconcile_Call {
	_c.Call.Return(run)
	return _c
}

// newMockAuthRegistrationReconciler creates a new instance of mockAuthRegistrationReconciler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAuthRegistrationReconciler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAuthRegistrationReconciler {
	mock := &mockAuthRegistrationReconciler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
