// Code generated by mockery v2.53.6. DO NOT EDIT.

package controller

import (
	"context"
	"net/http"

	"github.com/go-logr/logr"
	"github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/events"
	"k8s.io/client-go/tools/record"
	"sigs.k8s.io/controller-runtime/pkg/cache"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/config"
	"sigs.k8s.io/controller-runtime/pkg/healthz"
	mgr "sigs.k8s.io/controller-runtime/pkg/manager"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/conversion"
)

// mockManager is an autogenerated mock type for the manager type
type mockManager struct {
	mock.Mock
}

type mockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockManager) EXPECT() *mockManager_Expecter {
	return &mockManager_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: _a0
func (_m *mockManager) Add(_a0 mgr.Runnable) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(mgr.Runnable) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockManager_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type mockManager_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - _a0 mgr.Runnable
func (_e *mockManager_Expecter) Add(_a0 interface{}) *mockManager_Add_Call {
	return &mockManager_Add_Call{Call: _e.mock.On("Add", _a0)}
}

func (_c *mockManager_Add_Call) Run(run func(_a0 mgr.Runnable)) *mockManager_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(mgr.Runnable))
	})
	return _c
}

func (_c *mockManager_Add_Call) Return(_a0 error) *mockManager_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_Add_Call) RunAndReturn(run func(mgr.Runnable) error) *mockManager_Add_Call {
	_c.Call.Return(run)
	return _c
}

// AddHealthzCheck provides a mock function with given fields: name, check
func (_m *mockManager) AddHealthzCheck(name string, check healthz.Checker) error {
	ret := _m.Called(name, check)

	if len(ret) == 0 {
		panic("no return value specified for AddHealthzCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, healthz.Checker) error); ok {
		r0 = rf(name, check)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockManager_AddHealthzCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHealthzCheck'
type mockManager_AddHealthzCheck_Call struct {
	*mock.Call
}

// AddHealthzCheck is a helper method to define mock.On call
//   - name string
//   - check healthz.Checker
func (_e *mockManager_Expecter) AddHealthzCheck(name interface{}, check interface{}) *mockManager_AddHealthzCheck_Call {
	return &mockManager_AddHealthzCheck_Call{Call: _e.mock.On("AddHealthzCheck", name, check)}
}

func (_c *mockManager_AddHealthzCheck_Call) Run(run func(name string, check healthz.Checker)) *mockManager_AddHealthzCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(healthz.Checker))
	})
	return _c
}

func (_c *mockManager_AddHealthzCheck_Call) Return(_a0 error) *mockManager_AddHealthzCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_AddHealthzCheck_Call) RunAndReturn(run func(string, healthz.Checker) error) *mockManager_AddHealthzCheck_Call {
	_c.Call.Return(run)
	return _c
}

// AddMetricsServerExtraHandler provides a mock function with given fields: path, handler
func (_m *mockManager) AddMetricsServerExtraHandler(path string, handler http.Handler) error {
	ret := _m.Called(path, handler)

	if len(ret) == 0 {
		panic("no return value specified for AddMetricsServerExtraHandler")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, http.Handler) error); ok {
		r0 = rf(path, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockManager_AddMetricsServerExtraHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMetricsServerExtraHandler'
type mockManager_AddMetricsServerExtraHandler_Call struct {
	*mock.Call
}

// AddMetricsServerExtraHandler is a helper method to define mock.On call
//   - path string
//   - handler http.Handler
func (_e *mockManager_Expecter) AddMetricsServerExtraHandler(path interface{}, handler interface{}) *mockManager_AddMetricsServerExtraHandler_Call {
	return &mockManager_AddMetricsServerExtraHandler_Call{Call: _e.mock.On("AddMetricsServerExtraHandler", path, handler)}
}

func (_c *mockManager_AddMetricsServerExtraHandler_Call) Run(run func(path string, handler http.Handler)) *mockManager_AddMetricsServerExtraHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(http.Handler))
	})
	return _c
}

func (_c *mockManager_AddMetricsServerExtraHandler_Call) Return(_a0 error) *mockManager_AddMetricsServerExtraHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_AddMetricsServerExtraHandler_Call) RunAndReturn(run func(string, http.Handler) error) *mockManager_AddMetricsServerExtraHandler_Call {
	_c.Call.Return(run)
	return _c
}

// AddReadyzCheck provides a mock function with given fields: name, check
func (_m *mockManager) AddReadyzCheck(name string, check healthz.Checker) error {
	ret := _m.Called(name, check)

	if len(ret) == 0 {
		panic("no return value specified for AddReadyzCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, healthz.Checker) error); ok {
		r0 = rf(name, check)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockManager_AddReadyzCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddReadyzCheck'
type mockManager_AddReadyzCheck_Call struct {
	*mock.Call
}

// AddReadyzCheck is a helper method to define mock.On call
//   - name string
//   - check healthz.Checker
func (_e *mockManager_Expecter) AddReadyzCheck(name interface{}, check interface{}) *mockManager_AddReadyzCheck_Call {
	return &mockManager_AddReadyzCheck_Call{Call: _e.mock.On("AddReadyzCheck", name, check)}
}

func (_c *mockManager_AddReadyzCheck_Call) Run(run func(name string, check healthz.Checker)) *mockManager_AddReadyzCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(healthz.Checker))
	})
	return _c
}

func (_c *mockManager_AddReadyzCheck_Call) Return(_a0 error) *mockManager_AddReadyzCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_AddReadyzCheck_Call) RunAndReturn(run func(string, healthz.Checker) error) *mockManager_AddReadyzCheck_Call {
	_c.Call.Return(run)
	return _c
}

// Elected provides a mock function with no fields
func (_m *mockManager) Elected() <-chan struct{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Elected")
	}

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	return r0
}

// mockManager_Elected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Elected'
type mockManager_Elected_Call struct {
	*mock.Call
}

// Elected is a helper method to define mock.On call
func (_e *mockManager_Expecter) Elected() *mockManager_Elected_Call {
	return &mockManager_Elected_Call{Call: _e.mock.On("Elected")}
}

func (_c *mockManager_Elected_Call) Run(run func()) *mockManager_Elected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockManager_Elected_Call) Return(_a0 <-chan struct{}) *mockManager_Elected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_Elected_Call) RunAndReturn(run func() <-chan struct{}) *mockManager_Elected_Call {
	_c.Call.Return(run)
	return _c
}

// GetAPIReader provides a mock function with no fields
func (_m *mockManager) GetAPIReader() client.Reader {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAPIReader")
	}

	var r0 client.Reader
	if rf, ok := ret.Get(0).(func() client.Reader); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Reader)
		}
	}

	return r0
}

// mockManager_GetAPIReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPIReader'
type mockManager_GetAPIReader_Call struct {
	*mock.Call
}

// GetAPIReader is a helper method to define mock.On call
func (_e *mockManager_Expecter) GetAPIReader() *mockManager_GetAPIReader_Call {
	return &mockManager_GetAPIReader_Call{Call: _e.mock.On("GetAPIReader")}
}

func (_c *mockManager_GetAPIReader_Call) Run(run func()) *mockManager_GetAPIReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockManager_GetAPIReader_Call) Return(_a0 client.Reader) *mockManager_GetAPIReader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_GetAPIReader_Call) RunAndReturn(run func() client.Reader) *mockManager_GetAPIReader_Call {
	_c.Call.Return(run)
	return _c
}

// GetCache provides a mock function with no fields
func (_m *mockManager) GetCache() cache.Cache {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCache")
	}

	var r0 cache.Cache
	if rf, ok := ret.Get(0).(func() cache.Cache); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cache.Cache)
		}
	}

	return r0
}

// mockManager_GetCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCache'
type mockManager_GetCache_Call struct {
	*mock.Call
}

// GetCache is a helper method to define mock.On call
func (_e *mockManager_Expecter) GetCache() *mockManager_GetCache_Call {
	return &mockManager_GetCache_Call{Call: _e.mock.On("GetCache")}
}

func (_c *mockManager_GetCache_Call) Run(run func()) *mockManager_GetCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockManager_GetCache_Call) Return(_a0 cache.Cache) *mockManager_GetCache_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_GetCache_Call) RunAndReturn(run func() cache.Cache) *mockManager_GetCache_Call {
	_c.Call.Return(run)
	return _c
}

// GetClient provides a mock function with no fields
func (_m *mockManager) GetClient() client.Client {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 client.Client
	if rf, ok := ret.Get(0).(func() client.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	return r0
}

// mockManager_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type mockManager_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
func (_e *mockManager_Expecter) GetClient() *mockManager_GetClient_Call {
	return &mockManager_GetClient_Call{Call: _e.mock.On("GetClient")}
}

func (_c *mockManager_GetClient_Call) Run(run func()) *mockManager_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockManager_GetClient_Call) Return(_a0 client.Client) *mockManager_GetClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_GetClient_Call) RunAndReturn(run func() client.Client) *mockManager_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function with no fields
func (_m *mockManager) GetConfig() *rest.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 *rest.Config
	if rf, ok := ret.Get(0).(func() *rest.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Config)
		}
	}

	return r0
}

// mockManager_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type mockManager_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *mockManager_Expecter) GetConfig() *mockManager_GetConfig_Call {
	return &mockManager_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *mockManager_GetConfig_Call) Run(run func()) *mockManager_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockManager_GetConfig_Call) Return(_a0 *rest.Config) *mockManager_GetConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_GetConfig_Call) RunAndReturn(run func() *rest.Config) *mockManager_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetControllerOptions provides a mock function with no fields
func (_m *mockManager) GetControllerOptions() config.Controller {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetControllerOptions")
	}

	var r0 config.Controller
	if rf, ok := ret.Get(0).(func() config.Controller); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.Controller)
	}

	return r0
}

// mockManager_GetControllerOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetControllerOptions'
type mockManager_GetControllerOptions_Call struct {
	*mock.Call
}

// GetControllerOptions is a helper method to define mock.On call
func (_e *mockManager_Expecter) GetControllerOptions() *mockManager_GetControllerOptions_Call {
	return &mockManager_GetControllerOptions_Call{Call: _e.mock.On("GetControllerOptions")}
}

func (_c *mockManager_GetControllerOptions_Call) Run(run func()) *mockManager_GetControllerOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockManager_GetControllerOptions_Call) Return(_a0 config.Controller) *mockManager_GetControllerOptions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_GetControllerOptions_Call) RunAndReturn(run func() config.Controller) *mockManager_GetControllerOptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetConverterRegistry provides a mock function with no fields
func (_m *mockManager) GetConverterRegistry() conversion.Registry {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConverterRegistry")
	}

	var r0 conversion.Registry
	if rf, ok := ret.Get(0).(func() conversion.Registry); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(conversion.Registry)
		}
	}

	return r0
}

// mockManager_GetConverterRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConverterRegistry'
type mockManager_GetConverterRegistry_Call struct {
	*mock.Call
}

// GetConverterRegistry is a helper method to define mock.On call
func (_e *mockManager_Expecter) GetConverterRegistry() *mockManager_GetConverterRegistry_Call {
	return &mockManager_GetConverterRegistry_Call{Call: _e.mock.On("GetConverterRegistry")}
}

func (_c *mockManager_GetConverterRegistry_Call) Run(run func()) *mockManager_GetConverterRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockManager_GetConverterRegistry_Call) Return(_a0 conversion.Registry) *mockManager_GetConverterRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_GetConverterRegistry_Call) RunAndReturn(run func() conversion.Registry) *mockManager_GetConverterRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventRecorder provides a mock function with given fields: name
func (_m *mockManager) GetEventRecorder(name string) events.EventRecorder {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetEventRecorder")
	}

	var r0 events.EventRecorder
	if rf, ok := ret.Get(0).(func(string) events.EventRecorder); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(events.EventRecorder)
		}
	}

	return r0
}

// mockManager_GetEventRecorder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventRecorder'
type mockManager_GetEventRecorder_Call struct {
	*mock.Call
}

// GetEventRecorder is a helper method to define mock.On call
//   - name string
func (_e *mockManager_Expecter) GetEventRecorder(name interface{}) *mockManager_GetEventRecorder_Call {
	return &mockManager_GetEventRecorder_Call{Call: _e.mock.On("GetEventRecorder", name)}
}

func (_c *mockManager_GetEventRecorder_Call) Run(run func(name string)) *mockManager_GetEventRecorder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockManager_GetEventRecorder_Call) Return(_a0 events.EventRecorder) *mockManager_GetEventRecorder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_GetEventRecorder_Call) RunAndReturn(run func(string) events.EventRecorder) *mockManager_GetEventRecorder_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventRecorderFor provides a mock function with given fields: name
func (_m *mockManager) GetEventRecorderFor(name string) record.EventRecorder {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetEventRecorderFor")
	}

	var r0 record.EventRecorder
	if rf, ok := ret.Get(0).(func(string) record.EventRecorder); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(record.EventRecorder)
		}
	}

	return r0
}

// mockManager_GetEventRecorderFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventRecorderFor'
type mockManager_GetEventRecorderFor_Call struct {
	*mock.Call
}

// GetEventRecorderFor is a helper method to define mock.On call
//   - name string
func (_e *mockManager_Expecter) GetEventRecorderFor(name interface{}) *mockManager_GetEventRecorderFor_Call {
	return &mockManager_GetEventRecorderFor_Call{Call: _e.mock.On("GetEventRecorderFor", name)}
}

func (_c *mockManager_GetEventRecorderFor_Call) Run(run func(name string)) *mockManager_GetEventRecorderFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockManager_GetEventRecorderFor_Call) Return(_a0 record.EventRecorder) *mockManager_GetEventRecorderFor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_GetEventRecorderFor_Call) RunAndReturn(run func(string) record.EventRecorder) *mockManager_GetEventRecorderFor_Call {
	_c.Call.Return(run)
	return _c
}

// GetFieldIndexer provides a mock function with no fields
func (_m *mockManager) GetFieldIndexer() client.FieldIndexer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFieldIndexer")
	}

	var r0 client.FieldIndexer
	if rf, ok := ret.Get(0).(func() client.FieldIndexer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.FieldIndexer)
		}
	}

	return r0
}

// mockManager_GetFieldIndexer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFieldIndexer'
type mockManager_GetFieldIndexer_Call struct {
	*mock.Call
}

// GetFieldIndexer is a helper method to define mock.On call
func (_e *mockManager_Expecter) GetFieldIndexer() *mockManager_GetFieldIndexer_Call {
	return &mockManager_GetFieldIndexer_Call{Call: _e.mock.On("GetFieldIndexer")}
}

func (_c *mockManager_GetFieldIndexer_Call) Run(run func()) *mockManager_GetFieldIndexer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockManager_GetFieldIndexer_Call) Return(_a0 client.FieldIndexer) *mockManager_GetFieldIndexer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_GetFieldIndexer_Call) RunAndReturn(run func() client.FieldIndexer) *mockManager_GetFieldIndexer_Call {
	_c.Call.Return(run)
	return _c
}

// GetHTTPClient provides a mock function with no fields
func (_m *mockManager) GetHTTPClient() *http.Client {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHTTPClient")
	}

	var r0 *http.Client
	if rf, ok := ret.Get(0).(func() *http.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Client)
		}
	}

	return r0
}

// mockManager_GetHTTPClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHTTPClient'
type mockManager_GetHTTPClient_Call struct {
	*mock.Call
}

// GetHTTPClient is a helper method to define mock.On call
func (_e *mockManager_Expecter) GetHTTPClient() *mockManager_GetHTTPClient_Call {
	return &mockManager_GetHTTPClient_Call{Call: _e.mock.On("GetHTTPClient")}
}

func (_c *mockManager_GetHTTPClient_Call) Run(run func()) *mockManager_GetHTTPClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockManager_GetHTTPClient_Call) Return(_a0 *http.Client) *mockManager_GetHTTPClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_GetHTTPClient_Call) RunAndReturn(run func() *http.Client) *mockManager_GetHTTPClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogger provides a mock function with no fields
func (_m *mockManager) GetLogger() logr.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 logr.Logger
	if rf, ok := ret.Get(0).(func() logr.Logger); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(logr.Logger)
	}

	return r0
}

// mockManager_GetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogger'
type mockManager_GetLogger_Call struct {
	*mock.Call
}

// GetLogger is a helper method to define mock.On call
func (_e *mockManager_Expecter) GetLogger() *mockManager_GetLogger_Call {
	return &mockManager_GetLogger_Call{Call: _e.mock.On("GetLogger")}
}

func (_c *mockManager_GetLogger_Call) Run(run func()) *mockManager_GetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockManager_GetLogger_Call) Return(_a0 logr.Logger) *mockManager_GetLogger_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_GetLogger_Call) RunAndReturn(run func() logr.Logger) *mockManager_GetLogger_Call {
	_c.Call.Return(run)
	return _c
}

// GetRESTMapper provides a mock function with no fields
func (_m *mockManager) GetRESTMapper() meta.RESTMapper {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRESTMapper")
	}

	var r0 meta.RESTMapper
	if rf, ok := ret.Get(0).(func() meta.RESTMapper); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(meta.RESTMapper)
		}
	}

	return r0
}

// mockManager_GetRESTMapper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRESTMapper'
type mockManager_GetRESTMapper_Call struct {
	*mock.Call
}

// GetRESTMapper is a helper method to define mock.On call
func (_e *mockManager_Expecter) GetRESTMapper() *mockManager_GetRESTMapper_Call {
	return &mockManager_GetRESTMapper_Call{Call: _e.mock.On("GetRESTMapper")}
}

func (_c *mockManager_GetRESTMapper_Call) Run(run func()) *mockManager_GetRESTMapper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockManager_GetRESTMapper_Call) Return(_a0 meta.RESTMapper) *mockManager_GetRESTMapper_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_GetRESTMapper_Call) RunAndReturn(run func() meta.RESTMapper) *mockManager_GetRESTMapper_Call {
	_c.Call.Return(run)
	return _c
}

// GetScheme provides a mock function with no fields
func (_m *mockManager) GetScheme() *runtime.Scheme {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetScheme")
	}

	var r0 *runtime.Scheme
	if rf, ok := ret.Get(0).(func() *runtime.Scheme); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*runtime.Scheme)
		}
	}

	return r0
}

// mockManager_GetScheme_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScheme'
type mockManager_GetScheme_Call struct {
	*mock.Call
}

// GetScheme is a helper method to define mock.On call
func (_e *mockManager_Expecter) GetScheme() *mockManager_GetScheme_Call {
	return &mockManager_GetScheme_Call{Call: _e.mock.On("GetScheme")}
}

func (_c *mockManager_GetScheme_Call) Run(run func()) *mockManager_GetScheme_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockManager_GetScheme_Call) Return(_a0 *runtime.Scheme) *mockManager_GetScheme_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_GetScheme_Call) RunAndReturn(run func() *runtime.Scheme) *mockManager_GetScheme_Call {
	_c.Call.Return(run)
	return _c
}

// GetWebhookServer provides a mock function with no fields
func (_m *mockManager) GetWebhookServer() webhook.Server {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetWebhookServer")
	}

	var r0 webhook.Server
	if rf, ok := ret.Get(0).(func() webhook.Server); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(webhook.Server)
		}
	}

	return r0
}

// mockManager_GetWebhookServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWebhookServer'
type mockManager_GetWebhookServer_Call struct {
	*mock.Call
}

// GetWebhookServer is a helper method to define mock.On call
func (_e *mockManager_Expecter) GetWebhookServer() *mockManager_GetWebhookServer_Call {
	return &mockManager_GetWebhookServer_Call{Call: _e.mock.On("GetWebhookServer")}
}

func (_c *mockManager_GetWebhookServer_Call) Run(run func()) *mockManager_GetWebhookServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockManager_GetWebhookServer_Call) Return(_a0 webhook.Server) *mockManager_GetWebhookServer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_GetWebhookServer_Call) RunAndReturn(run func() webhook.Server) *mockManager_GetWebhookServer_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *mockManager) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockManager_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type mockManager_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockManager_Expecter) Start(ctx interface{}) *mockManager_Start_Call {
	return &mockManager_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *mockManager_Start_Call) Run(run func(ctx context.Context)) *mockManager_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockManager_Start_Call) Return(_a0 error) *mockManager_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockManager_Start_Call) RunAndReturn(run func(context.Context) error) *mockManager_Start_Call {
	_c.Call.Return(run)
	return _c
}

// newMockManager creates a new instance of mockmgr. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockManager {
	mock := &mockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
