// Code generated by mockery v2.53.3. DO NOT EDIT.

package controller

import (
	context "context"

	v1 "github.com/cloudogu/k8s-auth-registration-lib/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// mockStatusPatcher is an autogenerated mock type for the statusPatcher type
type mockStatusPatcher struct {
	mock.Mock
}

type mockStatusPatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStatusPatcher) EXPECT() *mockStatusPatcher_Expecter {
	return &mockStatusPatcher_Expecter{mock: &_m.Mock}
}

// PatchCredentialsPublished provides a mock function with given fields: ctx, authRegistration
func (_m *mockStatusPatcher) PatchCredentialsPublished(ctx context.Context, authRegistration *v1.AuthRegistration) error {
	ret := _m.Called(ctx, authRegistration)

	if len(ret) == 0 {
		panic("no return value specified for PatchCredentialsPublished")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.AuthRegistration) error); ok {
		r0 = rf(ctx, authRegistration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockStatusPatcher_PatchCredentialsPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchCredentialsPublished'
type mockStatusPatcher_PatchCredentialsPublished_Call struct {
	*mock.Call
}

// PatchCredentialsPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - authRegistration *v1.AuthRegistration
func (_e *mockStatusPatcher_Expecter) PatchCredentialsPublished(ctx interface{}, authRegistration interface{}) *mockStatusPatcher_PatchCredentialsPublished_Call {
	return &mockStatusPatcher_PatchCredentialsPublished_Call{Call: _e.mock.On("PatchCredentialsPublished", ctx, authRegistration)}
}

func (_c *mockStatusPatcher_PatchCredentialsPublished_Call) Run(run func(ctx context.Context, authRegistration *v1.AuthRegistration)) *mockStatusPatcher_PatchCredentialsPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.AuthRegistration))
	})
	return _c
}

func (_c *mockStatusPatcher_PatchCredentialsPublished_Call) Return(_a0 error) *mockStatusPatcher_PatchCredentialsPublished_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockStatusPatcher_PatchCredentialsPublished_Call) RunAndReturn(run func(context.Context, *v1.AuthRegistration) error) *mockStatusPatcher_PatchCredentialsPublished_Call {
	_c.Call.Return(run)
	return _c
}

// PatchInvalidSpec provides a mock function with given fields: ctx, authRegistration, invalidSpecErr
func (_m *mockStatusPatcher) PatchInvalidSpec(ctx context.Context, authRegistration *v1.AuthRegistration, invalidSpecErr error) error {
	ret := _m.Called(ctx, authRegistration, invalidSpecErr)

	if len(ret) == 0 {
		panic("no return value specified for PatchInvalidSpec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.AuthRegistration, error) error); ok {
		r0 = rf(ctx, authRegistration, invalidSpecErr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockStatusPatcher_PatchInvalidSpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchInvalidSpec'
type mockStatusPatcher_PatchInvalidSpec_Call struct {
	*mock.Call
}

// PatchInvalidSpec is a helper method to define mock.On call
//   - ctx context.Context
//   - authRegistration *v1.AuthRegistration
//   - invalidSpecErr error
func (_e *mockStatusPatcher_Expecter) PatchInvalidSpec(ctx interface{}, authRegistration interface{}, invalidSpecErr interface{}) *mockStatusPatcher_PatchInvalidSpec_Call {
	return &mockStatusPatcher_PatchInvalidSpec_Call{Call: _e.mock.On("PatchInvalidSpec", ctx, authRegistration, invalidSpecErr)}
}

func (_c *mockStatusPatcher_PatchInvalidSpec_Call) Run(run func(ctx context.Context, authRegistration *v1.AuthRegistration, invalidSpecErr error)) *mockStatusPatcher_PatchInvalidSpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.AuthRegistration), args[2].(error))
	})
	return _c
}

func (_c *mockStatusPatcher_PatchInvalidSpec_Call) Return(_a0 error) *mockStatusPatcher_PatchInvalidSpec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockStatusPatcher_PatchInvalidSpec_Call) RunAndReturn(run func(context.Context, *v1.AuthRegistration, error) error) *mockStatusPatcher_PatchInvalidSpec_Call {
	_c.Call.Return(run)
	return _c
}

// PatchRegistrationFailed provides a mock function with given fields: ctx, authRegistration, registrationErr
func (_m *mockStatusPatcher) PatchRegistrationFailed(ctx context.Context, authRegistration *v1.AuthRegistration, registrationErr error) error {
	ret := _m.Called(ctx, authRegistration, registrationErr)

	if len(ret) == 0 {
		panic("no return value specified for PatchRegistrationFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.AuthRegistration, error) error); ok {
		r0 = rf(ctx, authRegistration, registrationErr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockStatusPatcher_PatchRegistrationFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchRegistrationFailed'
type mockStatusPatcher_PatchRegistrationFailed_Call struct {
	*mock.Call
}

// PatchRegistrationFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - authRegistration *v1.AuthRegistration
//   - registrationErr error
func (_e *mockStatusPatcher_Expecter) PatchRegistrationFailed(ctx interface{}, authRegistration interface{}, registrationErr interface{}) *mockStatusPatcher_PatchRegistrationFailed_Call {
	return &mockStatusPatcher_PatchRegistrationFailed_Call{Call: _e.mock.On("PatchRegistrationFailed", ctx, authRegistration, registrationErr)}
}

func (_c *mockStatusPatcher_PatchRegistrationFailed_Call) Run(run func(ctx context.Context, authRegistration *v1.AuthRegistration, registrationErr error)) *mockStatusPatcher_PatchRegistrationFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.AuthRegistration), args[2].(error))
	})
	return _c
}

func (_c *mockStatusPatcher_PatchRegistrationFailed_Call) Return(_a0 error) *mockStatusPatcher_PatchRegistrationFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockStatusPatcher_PatchRegistrationFailed_Call) RunAndReturn(run func(context.Context, *v1.AuthRegistration, error) error) *mockStatusPatcher_PatchRegistrationFailed_Call {
	_c.Call.Return(run)
	return _c
}

// PatchRegistrationSucceeded provides a mock function with given fields: ctx, authRegistration
func (_m *mockStatusPatcher) PatchRegistrationSucceeded(ctx context.Context, authRegistration *v1.AuthRegistration) error {
	ret := _m.Called(ctx, authRegistration)

	if len(ret) == 0 {
		panic("no return value specified for PatchRegistrationSucceeded")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.AuthRegistration) error); ok {
		r0 = rf(ctx, authRegistration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockStatusPatcher_PatchRegistrationSucceeded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchRegistrationSucceeded'
type mockStatusPatcher_PatchRegistrationSucceeded_Call struct {
	*mock.Call
}

// PatchRegistrationSucceeded is a helper method to define mock.On call
//   - ctx context.Context
//   - authRegistration *v1.AuthRegistration
func (_e *mockStatusPatcher_Expecter) PatchRegistrationSucceeded(ctx interface{}, authRegistration interface{}) *mockStatusPatcher_PatchRegistrationSucceeded_Call {
	return &mockStatusPatcher_PatchRegistrationSucceeded_Call{Call: _e.mock.On("PatchRegistrationSucceeded", ctx, authRegistration)}
}

func (_c *mockStatusPatcher_PatchRegistrationSucceeded_Call) Run(run func(ctx context.Context, authRegistration *v1.AuthRegistration)) *mockStatusPatcher_PatchRegistrationSucceeded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.AuthRegistration))
	})
	return _c
}

func (_c *mockStatusPatcher_PatchRegistrationSucceeded_Call) Return(_a0 error) *mockStatusPatcher_PatchRegistrationSucceeded_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockStatusPatcher_PatchRegistrationSucceeded_Call) RunAndReturn(run func(context.Context, *v1.AuthRegistration) error) *mockStatusPatcher_PatchRegistrationSucceeded_Call {
	_c.Call.Return(run)
	return _c
}

// PatchResolvedSecretRef provides a mock function with given fields: ctx, authRegistration, resolvedSecretRef
func (_m *mockStatusPatcher) PatchResolvedSecretRef(ctx context.Context, authRegistration *v1.AuthRegistration, resolvedSecretRef string) error {
	ret := _m.Called(ctx, authRegistration, resolvedSecretRef)

	if len(ret) == 0 {
		panic("no return value specified for PatchResolvedSecretRef")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.AuthRegistration, string) error); ok {
		r0 = rf(ctx, authRegistration, resolvedSecretRef)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockStatusPatcher_PatchResolvedSecretRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchResolvedSecretRef'
type mockStatusPatcher_PatchResolvedSecretRef_Call struct {
	*mock.Call
}

// PatchResolvedSecretRef is a helper method to define mock.On call
//   - ctx context.Context
//   - authRegistration *v1.AuthRegistration
//   - resolvedSecretRef string
func (_e *mockStatusPatcher_Expecter) PatchResolvedSecretRef(ctx interface{}, authRegistration interface{}, resolvedSecretRef interface{}) *mockStatusPatcher_PatchResolvedSecretRef_Call {
	return &mockStatusPatcher_PatchResolvedSecretRef_Call{Call: _e.mock.On("PatchResolvedSecretRef", ctx, authRegistration, resolvedSecretRef)}
}

func (_c *mockStatusPatcher_PatchResolvedSecretRef_Call) Run(run func(ctx context.Context, authRegistration *v1.AuthRegistration, resolvedSecretRef string)) *mockStatusPatcher_PatchResolvedSecretRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.AuthRegistration), args[2].(string))
	})
	return _c
}

func (_c *mockStatusPatcher_PatchResolvedSecretRef_Call) Return(_a0 error) *mockStatusPatcher_PatchResolvedSecretRef_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockStatusPatcher_PatchResolvedSecretRef_Call) RunAndReturn(run func(context.Context, *v1.AuthRegistration, string) error) *mockStatusPatcher_PatchResolvedSecretRef_Call {
	_c.Call.Return(run)
	return _c
}

// PatchSecretReconcileFailed provides a mock function with given fields: ctx, authRegistration, resolvedSecretRef, secretErr
func (_m *mockStatusPatcher) PatchSecretReconcileFailed(ctx context.Context, authRegistration *v1.AuthRegistration, resolvedSecretRef string, secretErr error) error {
	ret := _m.Called(ctx, authRegistration, resolvedSecretRef, secretErr)

	if len(ret) == 0 {
		panic("no return value specified for PatchSecretReconcileFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.AuthRegistration, string, error) error); ok {
		r0 = rf(ctx, authRegistration, resolvedSecretRef, secretErr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockStatusPatcher_PatchSecretReconcileFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchSecretReconcileFailed'
type mockStatusPatcher_PatchSecretReconcileFailed_Call struct {
	*mock.Call
}

// PatchSecretReconcileFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - authRegistration *v1.AuthRegistration
//   - resolvedSecretRef string
//   - secretErr error
func (_e *mockStatusPatcher_Expecter) PatchSecretReconcileFailed(ctx interface{}, authRegistration interface{}, resolvedSecretRef interface{}, secretErr interface{}) *mockStatusPatcher_PatchSecretReconcileFailed_Call {
	return &mockStatusPatcher_PatchSecretReconcileFailed_Call{Call: _e.mock.On("PatchSecretReconcileFailed", ctx, authRegistration, resolvedSecretRef, secretErr)}
}

func (_c *mockStatusPatcher_PatchSecretReconcileFailed_Call) Run(run func(ctx context.Context, authRegistration *v1.AuthRegistration, resolvedSecretRef string, secretErr error)) *mockStatusPatcher_PatchSecretReconcileFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.AuthRegistration), args[2].(string), args[3].(error))
	})
	return _c
}

func (_c *mockStatusPatcher_PatchSecretReconcileFailed_Call) Return(_a0 error) *mockStatusPatcher_PatchSecretReconcileFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockStatusPatcher_PatchSecretReconcileFailed_Call) RunAndReturn(run func(context.Context, *v1.AuthRegistration, string, error) error) *mockStatusPatcher_PatchSecretReconcileFailed_Call {
	_c.Call.Return(run)
	return _c
}

// newMockStatusPatcher creates a new instance of mockStatusPatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStatusPatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStatusPatcher {
	mock := &mockStatusPatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
