// Code generated by mockery v2.53.3. DO NOT EDIT.

package cas

import (
	context "context"

	domain "github.com/cloudogu/k8s-auth-registration-operator/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// mockRegistrationMapper is an autogenerated mock type for the registrationMapper type
type mockRegistrationMapper struct {
	mock.Mock
}

type mockRegistrationMapper_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRegistrationMapper) EXPECT() *mockRegistrationMapper_Expecter {
	return &mockRegistrationMapper_Expecter{mock: &_m.Mock}
}

// BuildRegistrationResult provides a mock function with given fields: reg, service, clientSecret
func (_m *mockRegistrationMapper) BuildRegistrationResult(reg domain.Registration, service RegisteredService, clientSecret string) (domain.RegistrationResult, error) {
	ret := _m.Called(reg, service, clientSecret)

	if len(ret) == 0 {
		panic("no return value specified for BuildRegistrationResult")
	}

	var r0 domain.RegistrationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Registration, RegisteredService, string) (domain.RegistrationResult, error)); ok {
		return rf(reg, service, clientSecret)
	}
	if rf, ok := ret.Get(0).(func(domain.Registration, RegisteredService, string) domain.RegistrationResult); ok {
		r0 = rf(reg, service, clientSecret)
	} else {
		r0 = ret.Get(0).(domain.RegistrationResult)
	}

	if rf, ok := ret.Get(1).(func(domain.Registration, RegisteredService, string) error); ok {
		r1 = rf(reg, service, clientSecret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRegistrationMapper_BuildRegistrationResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildRegistrationResult'
type mockRegistrationMapper_BuildRegistrationResult_Call struct {
	*mock.Call
}

// BuildRegistrationResult is a helper method to define mock.On call
//   - reg domain.Registration
//   - service RegisteredService
//   - clientSecret string
func (_e *mockRegistrationMapper_Expecter) BuildRegistrationResult(reg interface{}, service interface{}, clientSecret interface{}) *mockRegistrationMapper_BuildRegistrationResult_Call {
	return &mockRegistrationMapper_BuildRegistrationResult_Call{Call: _e.mock.On("BuildRegistrationResult", reg, service, clientSecret)}
}

func (_c *mockRegistrationMapper_BuildRegistrationResult_Call) Run(run func(reg domain.Registration, service RegisteredService, clientSecret string)) *mockRegistrationMapper_BuildRegistrationResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Registration), args[1].(RegisteredService), args[2].(string))
	})
	return _c
}

func (_c *mockRegistrationMapper_BuildRegistrationResult_Call) Return(_a0 domain.RegistrationResult, _a1 error) *mockRegistrationMapper_BuildRegistrationResult_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRegistrationMapper_BuildRegistrationResult_Call) RunAndReturn(run func(domain.Registration, RegisteredService, string) (domain.RegistrationResult, error)) *mockRegistrationMapper_BuildRegistrationResult_Call {
	_c.Call.Return(run)
	return _c
}

// BuildServicePayload provides a mock function with given fields: ctx, reg, existing, services, clientSecret
func (_m *mockRegistrationMapper) BuildServicePayload(ctx context.Context, reg domain.Registration, existing *RegisteredService, services []RegisteredService, clientSecret string) (RegisteredService, error) {
	ret := _m.Called(ctx, reg, existing, services, clientSecret)

	if len(ret) == 0 {
		panic("no return value specified for BuildServicePayload")
	}

	var r0 RegisteredService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Registration, *RegisteredService, []RegisteredService, string) (RegisteredService, error)); ok {
		return rf(ctx, reg, existing, services, clientSecret)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Registration, *RegisteredService, []RegisteredService, string) RegisteredService); ok {
		r0 = rf(ctx, reg, existing, services, clientSecret)
	} else {
		r0 = ret.Get(0).(RegisteredService)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Registration, *RegisteredService, []RegisteredService, string) error); ok {
		r1 = rf(ctx, reg, existing, services, clientSecret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRegistrationMapper_BuildServicePayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildServicePayload'
type mockRegistrationMapper_BuildServicePayload_Call struct {
	*mock.Call
}

// BuildServicePayload is a helper method to define mock.On call
//   - ctx context.Context
//   - reg domain.Registration
//   - existing *RegisteredService
//   - services []RegisteredService
//   - clientSecret string
func (_e *mockRegistrationMapper_Expecter) BuildServicePayload(ctx interface{}, reg interface{}, existing interface{}, services interface{}, clientSecret interface{}) *mockRegistrationMapper_BuildServicePayload_Call {
	return &mockRegistrationMapper_BuildServicePayload_Call{Call: _e.mock.On("BuildServicePayload", ctx, reg, existing, services, clientSecret)}
}

func (_c *mockRegistrationMapper_BuildServicePayload_Call) Run(run func(ctx context.Context, reg domain.Registration, existing *RegisteredService, services []RegisteredService, clientSecret string)) *mockRegistrationMapper_BuildServicePayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Registration), args[2].(*RegisteredService), args[3].([]RegisteredService), args[4].(string))
	})
	return _c
}

func (_c *mockRegistrationMapper_BuildServicePayload_Call) Return(_a0 RegisteredService, _a1 error) *mockRegistrationMapper_BuildServicePayload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRegistrationMapper_BuildServicePayload_Call) RunAndReturn(run func(context.Context, domain.Registration, *RegisteredService, []RegisteredService, string) (RegisteredService, error)) *mockRegistrationMapper_BuildServicePayload_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRegistration provides a mock function with given fields: reg
func (_m *mockRegistrationMapper) ValidateRegistration(reg domain.Registration) error {
	ret := _m.Called(reg)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRegistration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Registration) error); ok {
		r0 = rf(reg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRegistrationMapper_ValidateRegistration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRegistration'
type mockRegistrationMapper_ValidateRegistration_Call struct {
	*mock.Call
}

// ValidateRegistration is a helper method to define mock.On call
//   - reg domain.Registration
func (_e *mockRegistrationMapper_Expecter) ValidateRegistration(reg interface{}) *mockRegistrationMapper_ValidateRegistration_Call {
	return &mockRegistrationMapper_ValidateRegistration_Call{Call: _e.mock.On("ValidateRegistration", reg)}
}

func (_c *mockRegistrationMapper_ValidateRegistration_Call) Run(run func(reg domain.Registration)) *mockRegistrationMapper_ValidateRegistration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Registration))
	})
	return _c
}

func (_c *mockRegistrationMapper_ValidateRegistration_Call) Return(_a0 error) *mockRegistrationMapper_ValidateRegistration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRegistrationMapper_ValidateRegistration_Call) RunAndReturn(run func(domain.Registration) error) *mockRegistrationMapper_ValidateRegistration_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRegistrationMapper creates a new instance of mockRegistrationMapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRegistrationMapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRegistrationMapper {
	mock := &mockRegistrationMapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
