// Code generated by mockery v2.53.3. DO NOT EDIT.

package cas

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockApiClient is an autogenerated mock type for the apiClient type
type mockApiClient struct {
	mock.Mock
}

type mockApiClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockApiClient) EXPECT() *mockApiClient_Expecter {
	return &mockApiClient_Expecter{mock: &_m.Mock}
}

// BaseURL provides a mock function with no fields
func (_m *mockApiClient) BaseURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BaseURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// mockApiClient_BaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BaseURL'
type mockApiClient_BaseURL_Call struct {
	*mock.Call
}

// BaseURL is a helper method to define mock.On call
func (_e *mockApiClient_Expecter) BaseURL() *mockApiClient_BaseURL_Call {
	return &mockApiClient_BaseURL_Call{Call: _e.mock.On("BaseURL")}
}

func (_c *mockApiClient_BaseURL_Call) Run(run func()) *mockApiClient_BaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockApiClient_BaseURL_Call) Return(_a0 string) *mockApiClient_BaseURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockApiClient_BaseURL_Call) RunAndReturn(run func() string) *mockApiClient_BaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// CreateService provides a mock function with given fields: ctx, service
func (_m *mockApiClient) CreateService(ctx context.Context, service RegisteredService) (RegisteredService, error) {
	ret := _m.Called(ctx, service)

	if len(ret) == 0 {
		panic("no return value specified for CreateService")
	}

	var r0 RegisteredService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, RegisteredService) (RegisteredService, error)); ok {
		return rf(ctx, service)
	}
	if rf, ok := ret.Get(0).(func(context.Context, RegisteredService) RegisteredService); ok {
		r0 = rf(ctx, service)
	} else {
		r0 = ret.Get(0).(RegisteredService)
	}

	if rf, ok := ret.Get(1).(func(context.Context, RegisteredService) error); ok {
		r1 = rf(ctx, service)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockApiClient_CreateService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateService'
type mockApiClient_CreateService_Call struct {
	*mock.Call
}

// CreateService is a helper method to define mock.On call
//   - ctx context.Context
//   - service RegisteredService
func (_e *mockApiClient_Expecter) CreateService(ctx interface{}, service interface{}) *mockApiClient_CreateService_Call {
	return &mockApiClient_CreateService_Call{Call: _e.mock.On("CreateService", ctx, service)}
}

func (_c *mockApiClient_CreateService_Call) Run(run func(ctx context.Context, service RegisteredService)) *mockApiClient_CreateService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(RegisteredService))
	})
	return _c
}

func (_c *mockApiClient_CreateService_Call) Return(_a0 RegisteredService, _a1 error) *mockApiClient_CreateService_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockApiClient_CreateService_Call) RunAndReturn(run func(context.Context, RegisteredService) (RegisteredService, error)) *mockApiClient_CreateService_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteService provides a mock function with given fields: ctx, id
func (_m *mockApiClient) DeleteService(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockApiClient_DeleteService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteService'
type mockApiClient_DeleteService_Call struct {
	*mock.Call
}

// DeleteService is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *mockApiClient_Expecter) DeleteService(ctx interface{}, id interface{}) *mockApiClient_DeleteService_Call {
	return &mockApiClient_DeleteService_Call{Call: _e.mock.On("DeleteService", ctx, id)}
}

func (_c *mockApiClient_DeleteService_Call) Run(run func(ctx context.Context, id int64)) *mockApiClient_DeleteService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *mockApiClient_DeleteService_Call) Return(_a0 error) *mockApiClient_DeleteService_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockApiClient_DeleteService_Call) RunAndReturn(run func(context.Context, int64) error) *mockApiClient_DeleteService_Call {
	_c.Call.Return(run)
	return _c
}

// ListServices provides a mock function with given fields: ctx
func (_m *mockApiClient) ListServices(ctx context.Context) ([]RegisteredService, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListServices")
	}

	var r0 []RegisteredService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]RegisteredService, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []RegisteredService); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]RegisteredService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockApiClient_ListServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServices'
type mockApiClient_ListServices_Call struct {
	*mock.Call
}

// ListServices is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockApiClient_Expecter) ListServices(ctx interface{}) *mockApiClient_ListServices_Call {
	return &mockApiClient_ListServices_Call{Call: _e.mock.On("ListServices", ctx)}
}

func (_c *mockApiClient_ListServices_Call) Run(run func(ctx context.Context)) *mockApiClient_ListServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockApiClient_ListServices_Call) Return(_a0 []RegisteredService, _a1 error) *mockApiClient_ListServices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockApiClient_ListServices_Call) RunAndReturn(run func(context.Context) ([]RegisteredService, error)) *mockApiClient_ListServices_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateService provides a mock function with given fields: ctx, service
func (_m *mockApiClient) UpdateService(ctx context.Context, service RegisteredService) (RegisteredService, error) {
	ret := _m.Called(ctx, service)

	if len(ret) == 0 {
		panic("no return value specified for UpdateService")
	}

	var r0 RegisteredService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, RegisteredService) (RegisteredService, error)); ok {
		return rf(ctx, service)
	}
	if rf, ok := ret.Get(0).(func(context.Context, RegisteredService) RegisteredService); ok {
		r0 = rf(ctx, service)
	} else {
		r0 = ret.Get(0).(RegisteredService)
	}

	if rf, ok := ret.Get(1).(func(context.Context, RegisteredService) error); ok {
		r1 = rf(ctx, service)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockApiClient_UpdateService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateService'
type mockApiClient_UpdateService_Call struct {
	*mock.Call
}

// UpdateService is a helper method to define mock.On call
//   - ctx context.Context
//   - service RegisteredService
func (_e *mockApiClient_Expecter) UpdateService(ctx interface{}, service interface{}) *mockApiClient_UpdateService_Call {
	return &mockApiClient_UpdateService_Call{Call: _e.mock.On("UpdateService", ctx, service)}
}

func (_c *mockApiClient_UpdateService_Call) Run(run func(ctx context.Context, service RegisteredService)) *mockApiClient_UpdateService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(RegisteredService))
	})
	return _c
}

func (_c *mockApiClient_UpdateService_Call) Return(_a0 RegisteredService, _a1 error) *mockApiClient_UpdateService_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockApiClient_UpdateService_Call) RunAndReturn(run func(context.Context, RegisteredService) (RegisteredService, error)) *mockApiClient_UpdateService_Call {
	_c.Call.Return(run)
	return _c
}

// newMockApiClient creates a new instance of mockApiClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockApiClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockApiClient {
	mock := &mockApiClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
