// Code generated by mockery v2.53.3. DO NOT EDIT.

package cas

import (
	context "context"

	config "github.com/cloudogu/k8s-registry-lib/config"
	mock "github.com/stretchr/testify/mock"
)

// mockGlobalConfigRepo is an autogenerated mock type for the globalConfigRepo type
type mockGlobalConfigRepo struct {
	mock.Mock
}

type mockGlobalConfigRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *mockGlobalConfigRepo) EXPECT() *mockGlobalConfigRepo_Expecter {
	return &mockGlobalConfigRepo_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: _a0
func (_m *mockGlobalConfigRepo) Get(_a0 context.Context) (config.GlobalConfig, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 config.GlobalConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (config.GlobalConfig, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) config.GlobalConfig); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(config.GlobalConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockGlobalConfigRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockGlobalConfigRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *mockGlobalConfigRepo_Expecter) Get(_a0 interface{}) *mockGlobalConfigRepo_Get_Call {
	return &mockGlobalConfigRepo_Get_Call{Call: _e.mock.On("Get", _a0)}
}

func (_c *mockGlobalConfigRepo_Get_Call) Run(run func(_a0 context.Context)) *mockGlobalConfigRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockGlobalConfigRepo_Get_Call) Return(_a0 config.GlobalConfig, _a1 error) *mockGlobalConfigRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockGlobalConfigRepo_Get_Call) RunAndReturn(run func(context.Context) (config.GlobalConfig, error)) *mockGlobalConfigRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// newMockGlobalConfigRepo creates a new instance of mockGlobalConfigRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockGlobalConfigRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockGlobalConfigRepo {
	mock := &mockGlobalConfigRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
