apiVersion: v1
values:
  images:
    authRegistrationOperator: cloudogu/k8s-auth-registration-operator:0.1.0
patches:
  values.yaml:
    manager:
      image:
        registry: "{{ registryFrom .images.authRegistrationOperator }}"
        repository: "{{ repositoryFrom .images.authRegistrationOperator }}"
        tag: "{{ tagFrom .images.authRegistrationOperator }}"
