global:
  imagePullSecrets:
    - name: "ces-container-registries"
manager:
  replicas: 1
  image:
    registry: docker.io
    repository: cloudogu/k8s-auth-registration-operator
    tag: 1.1.1
  imagePullPolicy: IfNotPresent
  env:
    logLevel: info
    stage: production
  cas:
    baseUrl: "http://cas:8080/cas/"
    timeout: 10s
    authSecret:
      name: "lop-idp-cas-actuator-auth"
      usernameKey: username
      passwordKey: password
  resourceLimits:
    memory: 128M
  resourceRequests:
    cpu: 50m
    memory: 128M
  networkPolicies:
    enabled: true
