apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "k8s-auth-registration-operator.labels" . | nindent 4 }}
  name: {{ include "k8s-auth-registration-operator.name" . }}-controller-manager